# Generated by Django 3.1.2 on 2020-11-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('water_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('station_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.station')),
                ('vehicle_type_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.vehicle_type')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField()),
                ('doj', models.DateField()),
                ('salary', models.IntegerField()),
                ('designation_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.designation')),
                ('station_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.station')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('pin', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('complainer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.complainer')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('leaving_time', models.DateTimeField(auto_now_add=True)),
                ('reaching_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=2000)),
                ('report_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.report')),
                ('staff_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.staff')),
                ('vehicle_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fireStationApp1.vehicle')),
            ],
        ),
    ]
